name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'npm'

      - name: 安装依赖并构建 Astro 项目
        run: |
          npm ci
          npm run build

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: 列出构建目录内容
        run: ls -la ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
